# Generated by Django 3.2.2 on 2021-06-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custemer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('mobileno', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('houseno', models.CharField(max_length=40)),
                ('area', models.CharField(max_length=40)),
                ('landmark', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
            ],
        ),
    ]
