# Generated by Django 3.2.2 on 2021-06-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomweb', '0002_custemer'),
    ]

    operations = [
        migrations.AddField(
            model_name='custemer',
            name='emailid',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
