# Generated by Django 3.2.2 on 2021-06-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomweb', '0003_custemer_emailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='custemer',
            name='totalprice',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
