# Generated by Django 3.2.2 on 2021-06-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomweb', '0004_custemer_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custemer',
            name='area',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='custemer',
            name='city',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='custemer',
            name='emailid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='custemer',
            name='houseno',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='custemer',
            name='landmark',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='custemer',
            name='mobileno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='custemer',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='custemer',
            name='pin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='custemer',
            name='state',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='custemer',
            name='totalprice',
            field=models.IntegerField(null=True),
        ),
    ]
